### ISSUE TITLE
This repo name is terrible

### ISSUE THREAD

**Issue by ziel5122** [JessDF/CST-320---Hot-Potato2.0#2]
Why are there so many '-'s

**Comment by JessDF** [comment]
I'm not sure why it did that, It was automatic

**Comment by JessDF** [comment]
Austin, What's wrong with the name. I removed the -s like you wanted

**Comment by JessDF** [comment]
I'm closing this issue - We can discuss in person and fix during class

**Comment by ziel5122** [comment]
I'd prefer is all communication took place via email from now on
